name: finance_management
description: 'finance management application'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  auto_route: ^9.3.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  json_annotation: ^4.7.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  lottie: ^3.3.1
  get_it: ^8.0.3
  logger: ^2.5.0
  easy_localization: ^3.0.3
  locale_gen: ^12.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.3.0
  build_runner: ^2.4.15
  build_web_compilers: ^4.0.3
  json_serializable: ^6.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/translations/


