// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfp-P2fhKs4vza7E8dX4cUqXpHHHcU18U',
    appId: '1:266486447050:web:7a7e01bdcce2ea96e52d33',
    messagingSenderId: '266486447050',
    projectId: 'finance-management-a3714',
    authDomain: 'finance-management-a3714.firebaseapp.com',
    storageBucket: 'finance-management-a3714.firebasestorage.app',
    measurementId: 'G-5PD29HH0QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRBaPud0w9nnKKpWvd2geVCVo8eX2skM',
    appId: '1:266486447050:android:2f8e2b3bc849df58e52d33',
    messagingSenderId: '266486447050',
    projectId: 'finance-management-a3714',
    storageBucket: 'finance-management-a3714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI6_Na-fkC0OZtF3WAz-ZjEANHNt7THRE',
    appId: '1:266486447050:ios:b6497366001fda6ce52d33',
    messagingSenderId: '266486447050',
    projectId: 'finance-management-a3714',
    storageBucket: 'finance-management-a3714.firebasestorage.app',
    iosBundleId: 'com.example.financeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI6_Na-fkC0OZtF3WAz-ZjEANHNt7THRE',
    appId: '1:266486447050:ios:b6497366001fda6ce52d33',
    messagingSenderId: '266486447050',
    projectId: 'finance-management-a3714',
    storageBucket: 'finance-management-a3714.firebasestorage.app',
    iosBundleId: 'com.example.financeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfp-P2fhKs4vza7E8dX4cUqXpHHHcU18U',
    appId: '1:266486447050:web:65669e4c2a940385e52d33',
    messagingSenderId: '266486447050',
    projectId: 'finance-management-a3714',
    authDomain: 'finance-management-a3714.firebaseapp.com',
    storageBucket: 'finance-management-a3714.firebasestorage.app',
    measurementId: 'G-F2PEFCMCYS',
  );
}
